<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInit85ce728670ebfb43ee7555fdaec5c284
{
    public static $prefixesPsr0 = array (
        'D' => 
        array (
            'Detection' => 
            array (
                0 => __DIR__ . '/..' . '/mobiledetect/mobiledetectlib/namespaced',
            ),
        ),
    );

    public static $classMap = array (
        'Mobile_Detect' => __DIR__ . '/..' . '/mobiledetect/mobiledetectlib/Mobile_Detect.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixesPsr0 = ComposerStaticInit85ce728670ebfb43ee7555fdaec5c284::$prefixesPsr0;
            $loader->classMap = ComposerStaticInit85ce728670ebfb43ee7555fdaec5c284::$classMap;

        }, null, ClassLoader::class);
    }
}
